### PR TITLE
Update snapshot

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by brunobasto** [comment]
@matuzalemsteles, are we good to merge this one?

**Comment by matuzalemsteles** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matuzalemsteles** [comment]
Merged 🎉

Thanks a lot @alinedoleron!!

**Comment by alinedoleron** [comment]
Thank you too, @matuzalemsteles! =D

**Pull request merged**
